### ISSUE TITLE
final classes

### ISSUE THREAD

**Issue by ShurikAg** [php-imagine/Imagine#162]
Hi, 

We are using this library for our project and we came across an issue that blocks us from extending the functionality and in particular the fact that quite a few classes defined as final.

What is the actual reason for these classes to be final?

**Comment by mlocati** [comment]
Me too I'd like to remove the final classes/methods.
We can follow semver if we have to break the backward compatibility.
So, I'll implement this before releasing the next version of Imagine (which should be 1.x) if there won't be any downvote from the other maintainers.
