### ISSUE TITLE
Imagick::thumbnailImage $fill parameter

### ISSUE THREAD

**Issue by aur1mas** [php-imagine/Imagine#203]
`Imagick::thumbnailImage` supports 4th parameter `$fill = false`, which fills empty space and provides image with exact width/height.
More info: http://lt1.php.net/manual/en/imagick.thumbnailimage.php

Is it possible to add this param through Imagine? If no, how it could be implemented? I could implement it & make pull request.

**Comment by mlocati** [comment]
You can always crop the image before making a thumbnail for it.
