### ISSUE TITLE
Imagine\Image\Point

### ISSUE THREAD

**Issue by bryglen** [php-imagine/Imagine#321]
the constructor on this class doesn't allow negative values on the Point

my scenario is this

I am making a collage picture and one of the image I want to start at -x and -y but the class doesn't allow Negative values on it. best example is make a collage map and the collage map is using negative values to the pictures rendered

![screen shot 2014-04-30 at 3 58 08 pm](https://cloud.githubusercontent.com/assets/875604/2838897/3f568d30-d03d-11e3-8d16-4babbe5d0abf.png)

and the bad thing is the class is in "Final" so I cannot extend the class for my own use case. would it better to remove the "Final" class

**Comment by mlocati** [comment]
Recent versions of Imagine have a PointSigned class that you can use to represent negative coordinates
