### ISSUE TITLE
Return from $image->histogram() not actually a histogram

### ISSUE THREAD

**Issue by danielrhodeswarp** [php-imagine/Imagine#379]
I'm struggling to immediately see any frequency information in the array returned from $image->histogram().

How can I, for example, use histogram() to work out the _predominant_ colour in an image?

Yours confusedly,
Daniel

**Comment by LMCom** [comment]
Oh, I just stumbled over this bug, too.
For clarification: http://en.wikipedia.org/wiki/Histogram

@danielrhodeswarp : After treating the collected colors with `array_unique()`, the information about the frequency of each color is lost.

If at least `array_unique()` wasn't used, we could calculate the frequency ourselves. But it is easy to implement the method yourself, using the current implementation as a template.
Excerpt from https://github.com/avalanche123/Imagine/blob/develop/src/Gd/Image.php#L484 :

```php
    public function histogram()
    {
        $size = $this->getSize();
        $colors = array();
        for ($x = 0, $width = $size->getWidth(); $x < $width; $x++) {
            for ($y = 0, $height = $size->getHeight(); $y < $height; $y++) {
                $colors[] = $this->getColorAt(new Point($x, $y));
            }
        }
        return array_unique($colors);
    }
```

**Comment by mlocati** [comment]
The histogram method doesn't actually return an histogram, but only a plain list of the different colors used in an image.

If you need a full histogram, a pull request is very welcome.
