### ISSUE TITLE
Using in Bundle standart function

### ISSUE THREAD

**Issue by vladimircape** [php-imagine/Imagine#441]
I use your lib using Imagine Symfony2 bundle.
I get ImageInterface object, it's resource type Imagick, how i can use some Imagick function using you bundle, for example i need roundCorners
using just Imagick 
$image = new \Imagick();
$image->roundCorners(5,3);
How to make the same by your bundle

**Comment by mlocati** [comment]
You can get the unterlying Imagick object by calling the `getImagick()` method.
