### ISSUE TITLE
feature request: animated gif frame timing

### ISSUE THREAD

**Issue by makakken** [php-imagine/Imagine#506]
Would be nice if it is possible to set the delay between each frame of an animated gif, as in the animted gif convention. 

_Otherwise working with complex animated gifs is a mess cause they're always timed wrong._

**Comment by makakken** [comment]
nope, i was just using the library to resize animated gifs, so to have the same timing like in the source-gif-frames would completely be enough

**Comment by mlocati** [comment]
You can use the `animate()` method of the objects returned by the layers.
