### ISSUE TITLE
fit resize mode

### ISSUE THREAD

**Issue by Grummfy** [php-imagine/Imagine#561]
Hello,
I think a fit option could be very helpfull.

Take a picture of size AxB with the fiot mode you can choose to resize it to A'xB', with a filling of a specific color or not(transparent), to crop parts or not.

So constant options : 
* FIT_STRETCH : resize to the box size without conserving the ration (resize)
* FIT_FILL : resize, but like a thumbnail, except it fill blank parts
* FIT_MAX : like thumbnail with inset mode
* FIT_CROP : like thumbnail with outset mode

I think it's a common image manipulation and it could be really helpfull.

**Comment by barrychapman** [comment]
Anyone know if theres a way to do this?

**Comment by mlocati** [comment]
You can use the thumbnail method and the ImageInterface::THUMBNAIL_... constants
