### ISSUE TITLE
GD does not support layer set 

### ISSUE THREAD

**Issue by kvachakhia** [php-imagine/Imagine#752]
### Issue description

[GD does not support layer set ]
My code: 
![image](https://user-images.githubusercontent.com/59822053/99642802-55886e00-2a65-11eb-8518-3eb5a1e0905c.png)

### What version of Imagine are you using?
1.2.4

### What's the PHP version you are using?
7.4

### What's the imaging library you are using [gd/imagick/gmagick/any]?

...

### Minimal PHP code to reproduce the error: 

```php

// Please write the PHP code that shows the issue
// Use only code of the Imagine library (no 3rd party PHP libraries)
// If you load an image, please provide it too so that we can replicate your issue

```

**Comment by ausi** [comment]
This is the expected behavior because the GD driver does not support layers or animated GIFs.

**Comment by kvachakhia** [comment]
@ausi but how I can make from images one gif?

**Comment by ausi** [comment]
By using one of the GMagick or IMagick drivers. The GD library does not support animated GIFs but IMagick and GMagick both are able to generate animated GIFs as far as I know.
