### ISSUE TITLE
Saving Lossless Webp?

### ISSUE THREAD

**Issue by jcogs-design** [php-imagine/Imagine#857]
### Issue description

Since php 8.1 the php GD library supports the saving of images in the webp lossless format using the construct:
```
imagewebp($image, 'image.webp', IMG_WEBP_LOSSLESS);
```
where IMG_WEBP_LOSSLESS is a constant set to the value 101.

The `saveOrOutput` method in the GD\Image.php class has an explicit check (line 734) to prevent the value of the quality parameter exceeding the bounds 0-100.

How in this case then can lossless webp images be saved?

**Comment by ausi** [comment]
With the IMagick driver you can use the option `'webp_lossless' => true`.
The GD driver does not support that currently, see https://github.com/php-imagine/Imagine/pull/858

**Comment by jcogs-design** [comment]
Not entirely sure on what basis this got closed.
That you can do lossless using a different library is nice, but that doesn't address the range constraint on GD (which appears to be the only reason GD won't do lossless currently).
No more useful closure than saying "use a different library" really. I thought this process would be more inclusive regarding actual issues, rather than whatever it is that is convenient.

**Comment by jcogs-design** [comment]
> With the IMagick driver you can use the option `'webp_lossless' => true`. The GD driver does not support that currently, see #858

Actually GD library does support this feature. See here https://php.watch/versions/8.1/gd-webp-lossless

**Comment by mlocati** [comment]
> Not entirely sure on what basis this got closed.
> That you can do lossless using a different library is nice, but that doesn't address the range constraint on GD

This issue has been closed because https://github.com/php-imagine/Imagine/pull/858 should fix it. What's wrong with that pull request?

**Comment by ausi** [comment]
> No more useful closure than saying "use a different library" really.

No that’s not what I meant. #858 adds the support of `'webp_lossless' => true` for the GD driver.

> > The GD driver does not support that currently, see #858
> 
> Actually GD library does support this feature.

Yes, the GD **library** does, but the GD **driver** did not. But as #858 was already merged since, the GD **driver** now also supports lossless WEBP images (it was not released yet so you have to install the `dev-develop` version in order to use it in your project).
